title: <p align="center"> Nalinikanta </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href=>LinkedIn</a> |
  <a href="https://github.com/prince-06">GitHub</a>
  
  <br>   
  I'm working as a Specialist in BOSCH with programming languagge like Java, Python, etc.
  Working in various domain like Telecom,Banking,Automotive etc for 7 years.
  <br>
  </p>



theme: jekyll-theme-minimal
